spec:
  project: default
  source:
    repoURL: https://github.com/Cyto989/argocd-example-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default

apps:
  - name: app-guestbook-1
  - name: app-guestbook-2
  - name: app-guestbook-3
  - name: app-guestbook-4
  - name: app-guestbook-5
  - name: app-guestbook-6
  - name: app-guestbook-7
  - name: app-guestbook-8
  - name: app-guestbook-9
  - name: app-guestbook-10
