apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-guestbook2
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: guestbook
  name: guestbook-helm-guestbook1
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook2
      release: guestbook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helm-guestbook2
        release: guestbook
    spec:
      containers:
        - image: quay.io/argoprojlabs/argocd-e2e-container:0.1
          imagePullPolicy: IfNotPresent
          name: helm-guestbook
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - sh
                - '-c'
                - sleep 15 && exit 0
            failureThreshold: 1
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 17
          resources:
            requests:
              cpu: 100m
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
