apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cron-workload-scaler-configmap-editor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cron-workload-scaler.labels" . | nindent 4 }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: cron-workload-scaler
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: cron-workload-scaler-configmap-editor
  apiGroup: rbac.authorization.k8s.io
