apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cron-workload-scaler.fullname" . }}-configmap-editor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cron-workload-scaler.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]
