affinity: {}
app:
  enabled: true
  minReplicas: 8
  maxReplicas: 11
  name: guestbook3
  targetCPUUtilizationPercentage: 50
  configmap:
    enabled: false
containerPort: 80
fullnameOverride: "guestbook3"
image:
  pullPolicy: IfNotPresent
  repository: quay.io/argoprojlabs/argocd-e2e-container
  tag: 0.1
ingress:
  enabled: false
  annotations: {}
  hosts:
    - chart-example.local
  path: /
  tls: []
nodeSelector: {}
resources:
  requests:
    cpu: 100m
service:
  port: 80
  type: ClusterIP
tolerations: []
global:
  configmap:
    enabled: false
# race-test-1782325912
# race-test-1782326046
# race-test-1782326061
# race-test-1782326072
# race-test-1782326084
# race-test-1782326106
# race-test-1782326148
# race-test-1782326723
# race-test-1782326734
# race-test-1782326747
# race-test-1782326800
# race-test-1782326810
# race-test-1782326822
# race-test-1782326832
# race-test-1782326843
# race-test-1782326853
